### ISSUE TITLE
No codes avilable to replicate the results. 

### ISSUE THREAD

**Issue by AviralKumarTiwari** [WadudSania/PaperReplication#1]
Dear Wadud Sania,
Though notes mention that "This contains code and results." but there are no codes and data to replicate the results. it would be great if codes and data for at least a pair of variables are provided so that one can replicate the results. It would be really good for your paper to receive more citations. 

Kind Regards
Aviral

**Comment by WadudSania** [comment]
Dear Aviral,

Thank you for your message.

Unfortunately, I encountered an issue with the code upload, which I wasn't aware of until I received your message. I now understand why other authors had to contact me via email regarding the code. The codes have been successfully uploaded. Unfortunately, we cannot share the data due to restrictions. Please note that I had to split the code into pairs due to limitations in PC capacity. It might be more convenient to use a loop and run the code on a powerful PC.

I hope this helps. 

Best,
Sania

**Comment by AviralKumarTiwari** [comment]
Dear Wadud Sania
Great, many thanks.

Kind Regards
Aviral
